= Regular expression to parse git-urls
:generated-regex-filename: regex_generated.asc

== Why

When I was trying to use https://github.com/firecow/gitlab-ci-local to test a local build for my project https://gitlab.ost.ch/db/dateng.git, I discovered that extracted parts of the git url were wrong.
Looking into the code unveiled a js-regex which was not right.

== Resources

Online editing and matching regular expressions:: https://www.debuggex.com
Structure of git urls:: https://git-scm.com/docs/git-fetch#URLS
Sample git urls from stackoverflow:: https://stackoverflow.com/a/2514986/542082

== Python/PCRE regular expression

In contrast to JavaScript, python and pcre expressions support named groups which simplifies understanding the different parts even without a visualizer.

[source%autofit,regex]
.First version which misinterpreted the repository name as host
----
^(?P<scheme>(?P<protocol>[\w]+)://)?((?P<user>.+)(:(?P<pass>.+))?@)?((?P<host>[\w\d.]+)(:(?P<port>[\d]+))?)?(?P<scporpath>[:/])?(?P<pathtorepo>(?P<namespace>[^/]+)/((?P<project>[^/]+)(\.git)?))/?$
----

[source,pythonverboseregexp]
.Verbose version capabale of parsing almost any git url
----
include::{generated-regex-filename}[tags=python-regex-verbose]
----

[source,pythonregexp]
.Final version capabale of parsing almost any git url
----
include::{generated-regex-filename}[tags=python-regex]
----

[source,jsregexp]
.Regular expression valid in JavaScript
----
include::{generated-regex-filename}[tags=javascript-regex]
----

== Test data

Test urls were taken from https://stackoverflow.com/a/2514986/542082 and extended slightly by me.

[source,text]
----
include::git-url-check.py[tags=test-urls]
----

== Sample Python program

To prove the regular expression correct, the `git-url-check.py` can be used to print out matched groups of the tested URL's.
It will also update the file `{generated-regex-filename}` which will contain the verbose regular expression and condensed versions for Python/pcre and JavaScript.

[source,python]
.Python sample program
----
include::git-url-check.py[]
----