= Regular expression to parse git-urls

== Why

When I was trying to use https://github.com/firecow/gitlab-ci-local to test a local build for my project https://gitlab.ost.ch/db/dateng.git, I discovered that extracted parts of the git url were wrong.
Looking into the code unveiled a js-regex which was not right.

== Resources

Online editing and matching regular expressions:: https://www.debuggex.com
Structure of git urls:: https://git-scm.com/docs/git-fetch#URLS
Sample git urls from stackoverflow:: https://stackoverflow.com/a/2514986/542082

== Python/PCRE regular expression

In contrast to JavaScript, python and pcre expressions support named groups which simplifies understanding the different parts even without a visualizer.

[source%autofit,regex]
.First version which misinterpreted the repository name as host
----
^(?P<scheme>(?P<protocol>[\w]+)://)?((?P<user>.+)(:(?P<pass>.+))?@)?((?P<host>[\w\d.]+)(:(?P<port>[\d]+))?)?(?P<scporpath>[:/])?(?P<pathtorepo>(?P<namespace>[^/]+)/((?P<project>[^/]+)(\.git)?))/?$
 |          ^-2---------------^   | ||          || |          ||  | ||                || |             || | |                 | |              |                  | ||                ||     | ||
 |                                | |^-4--------^| ^-6--------^|  | |^-8--------------^| ^-10----------^| | ^-11--------------^ |              ^-13---------------^ |^-15-------------^^-16--^ ||
 |                                | |            ^-5-----------^  | |                  ^-9--------------^ |                     |                                 ^-14-------------------------^|
 ^-1------------------------------^ ^-3---------------------------^ ^-7-----------------------------------^                     ^-12------------------------------------------------------------^
----

[source,regexp]
.Final version capabale of parsing almost any git url
----
(?m)^(?P<scheme>(?P<protocol>[\w]+)://)?(?P<credentials>(?P<user>.+)(:(?P<pass>.+))?@)?((?P<fqdn>(?P<host>([\w\d]+)(\.[\w\d]+)+)(:(?P<port>[\d]+))?)(?=[:/]))?((?P<scporpath>[:/])?(?P<pathtorepo>(?P<namespace>([^/]+/)+)?(?P<project>[^/]+(\.git)?)))/?$
----

[source,pythonverboseregexp]
.Final version capabale of parsing almost any git url
----
(?m)
^
  (?P<scheme>
    (?P<protocol>[\w]+)
    ://
  )?
  (?P<credentials>
    (?P<user>.+)
    (:
      (?P<pass>.+)
    )?
    @
  )?
  (
    (?P<fqdn>
      (?P<host>
        ([\w\d]+)
        (\.[\w\d]+)+
      )
      (:
        (?P<port>[\d]+)
      )?
    )
    (?=[:/])
  )?
  (
    (?P<scporpath>[:/])?
    (?P<pathtorepo>
      (?P<namespace>
        ([^/]+/)+
      )?
      (?P<project>[^/]+
        (\.git)?
      )
    )
  )
  /?
$
----

[source,jsregexp]
.Regular expression valid in JavaScript
----
/^(([\w]+):\/\/)?((.+)(:(.+))?@)?(((([\w\d]+)(\.[\w\d]+)+)(:([\d]+))?)(?=[:\/]))?(([:\/])?((([^\/]+\/)+)?([^\/]+(\.git)?)))\/?$/
----

== Test data

Test urls were taken from https://stackoverflow.com/a/2514986/542082 and extended slightly by me.

[source,text]
----
ssh://user@host.xz:1234/path/to/repo.git/
ssh://user@host.xz/path/to/repo.git/
ssh://host.xz:1234/path/to/repo.git/
ssh://host.xz/path/to/repo.git/
ssh://user@host.xz/path/to/repo.git/
ssh://host.xz/path/to/repo.git/
ssh://user@host.xz/~user/path/to/repo.git/
ssh://host.xz/~user/path/to/repo.git/
ssh://user@host.xz/~/path/to/repo.git
ssh://host.xz/~/path/to/repo.git
user@host.xz:/path/to/repo.git/
host.xz:/path/to/repo.git/
user@host.xz:~user/path/to/repo.git/
host.xz:~user/path/to/repo.git/
user@host.xz:path/to/repo.git
host.xz:path/to/repo.git
rsync://host.xz/path/to/repo.git/
git://host.xz/path/to/repo.git/
git://host.xz/~user/path/to/repo.git/
http://host.xz/path/to/repo.git/
https://host.xz/path/to/repo.git/
https://user@host.xz/path/to/repo.git/
https://user:passwd@host.xz/path/to/repo.git/
https://user:passwd@host.xz:1234/path/to/repo.git/
/path/to/repo.git/
path/to/repo.git/
~/path/to/repo.git
file:///path/to/repo.git/
file://~/path/to/repo.git/
repo.git
./path:repo.git
git://github.com/justgord/.git
----

[source,python]
.python sample
----
import re

urls=[
    'ssh://user@host.xz:1234/path/to/repo.git/',
    'ssh://user@host.xz/path/to/repo.git/',
    'ssh://host.xz:1234/path/to/repo.git/',
    'ssh://host.xz/path/to/repo.git/',
    'ssh://user@host.xz/path/to/repo.git/',
    'ssh://host.xz/path/to/repo.git/',
    'ssh://user@host.xz/~user/path/to/repo.git/',
    'ssh://host.xz/~user/path/to/repo.git/',
    'ssh://user@host.xz/~/path/to/repo.git',
    'ssh://host.xz/~/path/to/repo.git',
    'user@host.xz:/path/to/repo.git/',
    'host.xz:/path/to/repo.git/',
    'user@host.xz:~user/path/to/repo.git/',
    'host.xz:~user/path/to/repo.git/',
    'user@host.xz:path/to/repo.git',
    'host.xz:path/to/repo.git',
    'rsync://host.xz/path/to/repo.git/',
    'git://host.xz/path/to/repo.git/',
    'git://host.xz/~user/path/to/repo.git/',
    'http://host.xz/path/to/repo.git/',
    'https://host.xz/path/to/repo.git/',
    'https://user@host.xz/path/to/repo.git/',
    'https://user:passwd@host.xz/path/to/repo.git/',
    'https://user:passwd@host.xz:1234/path/to/repo.git/',
    '/path/to/repo.git/',
    'path/to/repo.git/',
    '~/path/to/repo.git',
    'file:///path/to/repo.git/',
    'file://~/path/to/repo.git/',
    'repo.git',
    './path:repo.git',
    'git://github.com/justgord/.git'
]
mr=re.compile(r'(?m)^(?P<scheme>(?P<protocol>[\w]+)://)?(?P<credentials>(?P<user>.+)(:(?P<pass>.+))?@)?((?P<fqdn>(?P<host>([\w\d]+)(\.[\w\d]+)+)(:(?P<port>[\d]+))?)(?=[:/]))?((?P<scporpath>[:/])?(?P<pathtorepo>(?P<namespace>([^/]+/)+)?(?P<project>[^/]+(\.git)?)))/?$')
for u in urls:
    mr.search(u).groupdict()
----